name: Build LaTeX document
on: [push, pull_request]
jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install texlive-base
      - run: sudo apt-get install texlive-latex-extra
      - run: sudo apt-get install texlive-fonts-recommended
      - run: sudo apt-get install texlive-lang-polish
  build:
    needs: prepare-env
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install texlive-base
      - run: sudo apt-get install texlive-latex-extra
      - run: sudo apt-get install texlive-fonts-recommended
      - run: sudo apt-get install texlive-lang-polish
      - uses: actions/checkout@v2
      - name: Build LaTeX document
        run: pdflatex -interaction=nonstopmode -halt-on-error -file-line-error szablon.tex
        # run: |
        # pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
        # bibtex main
        # pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
        # pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
      - uses: actions/upload-artifact@v2
        with:
          name: szablon.pdf
          path: szablon.pdf
