name: Build LaTeX document
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install texlive-base
      - run: sudo apt-get install texlive-latex-extra
      - run: sudo apt-get install texlive-fonts-recommended
      - run: sudo apt-get install texlive-latex-recommended
      - run: sudo apt-get install texlive-lang-polish
      - run: sudo apt-get install texlive-bibtex-extra
      - run: sudo apt-get install biber
      - name: Checkout repository 
        uses: actions/checkout@v2
      - name: Build LaTeX document
        # run: pdflatex -interaction=nonstopmode -halt-on-error -file-line-error thesis_jb.tex
        run: pdflatex thesis_jb.tex
        # run: |
        # pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
        # bibtex main
        # pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
        # pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
      - uses: actions/upload-artifact@v2
        with:
          name: thesis_jb.pdf
          path: thesis_jb.pdf
